# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php70-pdo_firebird/Makefile 468352 2018-04-26 14:47:42Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
