# $FreeBSD: head/mail/php72-imap/Makefile 545454 2020-08-19 21:29:37Z tz $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-imap

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
