# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pecl-request/Makefile 512557 2019-09-22 07:14:00Z antoine $

PORTNAME=	request
PORTVERSION=	1.0.0b1
CATEGORIES=	devel

MAINTAINER=	gasol.wu@gmail.com
COMMENT=	Provides server-side request and response objects for PHP 7

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		php:pecl
IGNORE_WITH_PHP=	72 73 74 80 81

.include <bsd.port.mk>
