# category security

.for ext in filter openssl
SUBDIR+=	php70-$(ext)
SUBDIR+=	php71-$(ext)
SUBDIR+=	php72-$(ext)
SUBDIR+=	php73-$(ext)
.endfor

SUBDIR+=	php70-mcrypt
SUBDIR+=	php71-mcrypt
SUBDIR+=	php71-hash
SUBDIR+=	php72-hash
SUBDIR+=	php73-hash
SUBDIR+=	php72-sodium
SUBDIR+=	php73-sodium

.include <bsd.port.subdir.mk>
