# databases category

.for ext in dba interbase mysqli odbc pdo pdo_dblib pdo_firebird pdo_mysql pdo_odbc pdo_pgsql pdo_sqlite pgsql sqlite3
SUBDIR+=	php70-$(ext)
SUBDIR+=	php71-$(ext)
SUBDIR+=	php72-$(ext)
SUBDIR+=	php73-$(ext)
.endfor

.include <bsd.port.subdir.mk>
