# $FreeBSD: head/databases/php72-pdo_pgsql/Makefile 507978 2019-08-03 18:28:12Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-pdo_pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
