# devel category

.for ext in gettext intl json pcntl readline shmop sysvmsg sysvsem sysvshm tokenizer
SUBDIR+=	php70-$(ext)
SUBDIR+=	php71-$(ext)
SUBDIR+=	php72-$(ext)
SUBDIR+=	php73-$(ext)
.endfor

SUBDIR+=	pecl-request

.include <bsd.port.subdir.mk>
