# category sysutils

.for ext in ctype dom enchant pspell simplexml wddx xml xmlreader xmlwriter xsl
SUBDIR+=	php70-$(ext)
SUBDIR+=	php71-$(ext)
SUBDIR+=	php72-$(ext)
SUBDIR+=	php73-$(ext)
.endfor

.include <bsd.port.subdir.mk>

