# $FreeBSD: head/databases/php71-pdo_pgsql/Makefile 507977 2019-08-03 18:26:07Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-pdo_pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
